
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

# PARADIGM outputs on TCGA, as found here: 
# https://gdc.cancer.gov/about-data/publications/PanCan-CellOfOrigin
# "PARADIGM Pathway Inference Matrix"
paradigm_url: "https://api.gdc.cancer.gov/data/7d4c0344-f018-4ab0-949a-09815f483480"
paradigm_dir: "data/paradigm/"

mofa_python: "~/envs/tcga/bin/python"

################################
# Simulation study config
################################

sim_params:
    corruption:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [300]
            corruption:
                kadd: [0.05, 0.25, 0.5]
                krem: [0.05, 0.25, 0.5]
                nadd: [0.05, 0.25, 0.5]
                nrem: [0.05, 0.25, 0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [2000]
                    n_lambda: [8]
        large:
            schema:
                m: [10000]
                k: [300]
                n: [80000]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [1000]
            corruption:
                kadd: [0.05, 0.5]
                krem: [0.05, 0.5]
                nadd: [0.05, 0.5]
                nrem: [0.05, 0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [1]
                    lambda_X: [0.0]
                    capacity: [25000000]
                    lr: [0.05]
                    max_epochs: [1000]
                    n_lambda: [8]
    noise:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [10.0, 1.0, 0.1, 0.01, 0.001]
                missing: [0.25]
            top_pwys: [300]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [2000]
                    n_lambda: [8]
        large:
            schema:
                m: [10000]
                k: [300]
                n: [80000]
            sim:
                snr: [10.0, 0.1]
                missing: [0.25]
            top_pwys: [1000]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [1]
                    lambda_X: [0.0]
                    capacity: [25000000]
                    lr: [0.05]
                    max_epochs: [1000]
                    n_lambda: [8]
    l1frac:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [300]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [0.0, 0.25, 0.5, 0.75, 1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [2000]
                    n_lambda: [8]
        large:
            schema:
                m: [10000]
                k: [300]
                n: [80000]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [1000]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [0.0, 0.5, 1.0]
                    use_gpu: [1]
                    lambda_X: [0.0]
                    capacity: [25000000]
                    lr: [0.05]
                    max_epochs: [1000]
                    n_lambda: [8]
    edge_shuffle:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [300]
            corruption: ["original=1", "shuffled=1"]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [0.5]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [2000]
                    n_lambda: [8]
        large:
            schema:
                m: [10000]
                k: [300]
                n: [80000]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [1000]
            corruption: ["original=1", "shuffled=1"]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [0.5]
                    use_gpu: [1]
                    lambda_X: [0.0]
                    capacity: [25000000]
                    lr: [0.05]
                    max_epochs: [1000]
                    n_lambda: [8]
    missingness:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.0, 0.25, 0.5, 0.75]
            top_pwys: [300]
            corruption:
                    kadd: [0.05]
                    krem: [0.5]
                    nadd: [0.05]
                    nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [2000]
                    n_lambda: [8]
        large:
            schema:
                m: [10000]
                k: [300]
                n: [80000]
            sim:
                snr: [1.0]
                missing: [0.0, 0.25, 0.5, 0.75]
            top_pwys: [1000]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 5
            methods:
                matfac:
                    l1_fraction: [1.0]
                    use_gpu: [1]
                    lambda_X: [0.0]
                    capacity: [25000000]
                    lr: [0.05]
                    max_epochs: [1000]
                    n_lambda: [8]
 


################################
# TCGA evaluations config
################################

tcga_regressions:
    data:
        heldout_ctypes: ["OV:GBM:LAML"]
        kept_ctypes: ["HNSC:CESC:ESCA:STAD"]
        #kept_ctypes: ["HNSC"]
    targets: ["pathologic_stage", "hpv_status", "survival", "ctype"] 
    cross_val_folds: 5
    pathways:
        top_pwys: [500]
    methods:
        matfac:
            configuration: ["fsard"]
            K: [5]
            max_epochs: [1000]
            capacity: [100000000000]
            lr: [0.05]
            print_iter: [1]
            var_filter: [0.05]
            verbosity: [2]
            fit_reg_weight: ["none"]
        #pca:
        #    k: [5]
        #    var_filter: [0.05]
        ##gsva:
        ##    k: [5]
        #paradigm:
        #    k: [5]
        #    var_filter: [0.05]
        #plier:
        #    k: [5]
        #mofa:
        #    k: [15]
        #    var_filter: [0.1]


tcga_ablation:
    data:
        heldout_ctypes: ["OV:GBM:LAML"]
    pathways:
        top_pwys: [1000]
    methods:
        matfac:
            configuration: ["basic", "ard", "fsard"]
            K: [20]
            max_epochs: [2000]
            capacity: [1000000000000]
            lr: [0.2]
            print_iter: [1]
            var_filter: [0.25]
            verbosity: [2]
            fit_reg_weight: ["none"]
            

