

output_dir = "temp/"


matfac_simulation_study:
    main_cpu_sims:
        sim_params:
            omic_types:
            
        fit_params:
    batch_sims:
        sim_params:
        fit_params:
    main_gpu_sims:
        sim_params:
        fit_params:


matfac_tcga_runs:
    main_cpu_runs:
    main_gpu_runs:


supervised_task_comparison:
    data_params:
    method_params:    
