
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

sim_replicates: 5

sim_data_params:
    snr: [9.0, 99.0]

tcga_data_params:
    heldout_ctypes: ["OV", "GBM", "LAML"]

pathway_params:
    topk: [300]
    addk: [10, 75]
    removek: [10, 75]
    addnode: [0.05, 0.25]
    removenode: [0.05, 0.25]

method_params:
    matfac:
        max_epochs: 1000
        lr: 0.02
        lambda_layer: 0.25 
        lambda_X: 0.1
        init_lambda_Y: 32.0
        gpu_capacity: 25000000
    #prior: NULL

