
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

################################
# Simulation study config
################################

sim_params:
    corruption:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [10.0] #, 1.0, 0.1, 0.01, 0.001]
                missing: [0.25]
            top_pwys: [300]
            corruption:
                kadd: [0.05] #, 0.25, 0.5]
                krem: [0.05] #, 0.25, 0.5]
                nadd: [0.05] #, 0.25, 0.5]
                nrem: [0.05] #, 0.25, 0.5]
            srep: 1
            methods:
                matfac:
                    l1_fraction: [0.5] #, 1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [100]
                    n_lambda: [8]
    l1frac:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [300]
            corruption:
                kadd: [0.05]
                krem: [0.5]
                nadd: [0.05]
                nrem: [0.5]
            srep: 1
            methods:
                matfac:
                    #l1_fraction: [0.0, 0.25, 0.5, 0.75, 1.0]
                    l1_fraction: [0.5,1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [100]
                    n_lambda: [8]
    edge_shuffle:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.25]
            top_pwys: [300]
            corruption: ["original=1", "shuffled=1"]
            srep: 1
            methods:
                matfac:
                    #l1_fraction: [0.0, 0.5, 1.0]
                    l1_fraction: [0.5]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [100]
                    n_lambda: [8]
    missingness:
        small:
            schema:
                m: [100]
                k: [30]
                n: [800]
            sim:
                snr: [1.0]
                missing: [0.0, 0.25] #, 0.5, 0.75]
            top_pwys: [300]
            corruption:
                    kadd: [0.05]
                    krem: [0.5]
                    nadd: [0.05]
                    nrem: [0.5]
            srep: 1
            methods:
                matfac:
                    l1_fraction: [0.5] #, 1.0]
                    use_gpu: [0]
                    lambda_X: [0.01]
                    capacity: [25000000]
                    lr: [0.07]
                    max_epochs: [100]
                    n_lambda: [8]
 


################################
# TCGA evaluations config
################################

tcga_data_params:
    heldout_ctypes: ["OV", "GBM", "LAML"]

tcga_pathway_params:
    tcga_topk: [300, 500]

tcga_method_params:
    matfac:
        capacity: [25000000]
        l1_fraction: [0.0, 0.5, 1.0]
        lambda_X: [0.01]
        lr: [0.07]
        max_epochs: [100]
        n_lambda: [8]


