
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

sim_replicates: 5
pathway_corruption_replicates: 3

sim_data_params:
    M: [100] #, 1000, 10000]
    K: [30] #, 300]
    N: [750] #, 7500, 75000]
    snr: [10.0, 1.0, 0.1, 0.01, 0.001] 

tcga_data_params:
    heldout_ctypes: ["OV", "GBM", "LAML"]

pathway_params:
    topk: [300], 
    addk: [0.05, 0.2, 0.5]
    removek: [0.05, 0.2, 0.5]
    addnode: [0.05, 0.25]
    removenode: [0.05, 0.25]

method_params:
    matfac:
        max_epochs: [10000]
        lr: [0.07]
        lambda_X: [0.01]
        n_lambda: [8]
        capacity: [25000000]
        l1_fraction: [0.0, 0.5, 1.0]
    #prior: NULL

