
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

sim_params:
    data_params:
        snr: [99.0]
        true_K: [300]
        reps: 1
        heldout_ctypes: []
    matfac_params:
        max_epochs: 1000
        lr: 0.05
        lambda_layer: 16.0 
        lambda_X: 0.1
        init_lambda_Y: 256.0
        used_K: [300]
        gpu_capacity: 25000000

tcga_params:
    data_params:
        heldout_ctypes: ["OV", "GBM", "LAML"]
    matfac_params:
        max_epochs: 1000
        lr: 0.05
        lambda_layer: 16.0 
        lambda_X: 0.1
        init_lambda_Y: 256.0
        used_K: [300]
        gpu_capacity: 25000000
