
result_dir: "temp/"
tcga_dir: "data/tcga/"

reactome_url: "https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.txt.gz" 
reactome_dir: "data/reactome/"

#sim_replicates: 5
sim_replicates: 1

sim_data_params:
    #snr: [9.0, 99.0]
    snr: [99.0]

tcga_data_params:
    heldout_ctypes: ["OV", "GBM", "LAML"]

pathway_params:
    #topk: [300]
    #addk: [10, 75]
    #removek: [10, 75]
    #addnode: [0.05, 0.25]
    #removenode: [0.05, 0.25]
    topk: ["toy"]
    addk: [0]
    removek: [0]
    addnode: [0.0]
    removenode: [0.0]

method_params:
    matfac:
        max_epochs: 5000
        lr: 0.01
        lambda_X: 0.01
        n_lambda: 8
        gpu_capacity: 25000000
    #prior: NULL

